<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKx6pxuG\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKx6pxuG/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKx6pxuG.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKx6pxuG\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKx6pxuG\App_KernelProdContainer([
    'container.build_hash' => 'Kx6pxuG',
    'container.build_id' => '3bc582c5',
    'container.build_time' => 1691726030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKx6pxuG');
